---
- name: Install nginx
  command: yum -y install {{ item }}
  with_items: [nginx]
  become: true

- service: name=nginx enabled=yes
  become: true

- file: >
    path={{ letsencrypt_www_dir }}/.well-known/acme-challenge/
    state=directory
    owner="root"
    group="root"
    mode=0755
  become: true

- name: Create nginx configuration from template
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=0644
  become: true
  notify: restart nginx

- service: name=nginx state=started
  become: true
